spring:
  application:
    name: flashlearn
  datasource:
    url: jdbc:mysql://localhost:3306/flashlearn?createDatabaseIfNotExist=true
    username: fl123
    password: alwayschange
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 minutes
    refreshTokenExpiration: 604800 # 7 days
gemini:
  apiKey: ${GEMINI_API_KEY}
